### ISSUE TITLE
編輯提案資料集：要新增新的提案資料，又新增不進去了。編輯舊的內容在完全沒有更動內容狀態下按儲存，也儲存失敗。

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#220]
資料已經全部輸入，底下評分也都先打1進去，但是出現「child "scores" fails because ["scores" is required]」，回列表頁看。確認資料沒有寫入。

畫面如下
![2018-09-24 5 20 16](https://user-images.githubusercontent.com/6219477/45945040-c61ad800-c01e-11e8-8cce-f9da5c421526.png)

**Comment by charlieworld** [comment]
### 問題分析

0. 在後台 'https://console.watchout.tw/lab/lab_bill_data_sets/1` 測試
1. 原封不動送出確認，出現 error 訊息為 `child "scores" fails because ["scores" is required]`
2. 檢視前端送出的payload裡面的確沒有 `scores` array
![bill_data_set_payload](https://user-images.githubusercontent.com/10896707/46008161-90ddbb00-c0ee-11e8-8b3d-8a4eeae75fc0.png)

### 可能的原因

提案評分 未正常讀取成功
![default](https://user-images.githubusercontent.com/10896707/46008214-b5399780-c0ee-11e8-91b7-f780ba635f99.png)
 

已測試過 API 的確是有回傳 `scores` 物件

URI : https://core.watchout.tw/console/lab/bill_data_sets/1

**Comment by charlieworld** [comment]
麻煩 @staristic  看一下此問題

**Comment by chihhhhhao** [comment]
- [x] Deploy
- [x] Test

**Comment by buttom** [comment]
可以用了。謝謝。
